baseurl = "https://www.aziogas.lt/"
title = "Ąžiogas"
theme = "PaperMod"
canonifyURLs = true
enableRobotsTXT = true

[Params]
    author = "Ąžuolas Krušna"
    mainSections = ["post"]
    intro = true
    headline = "My headline"
    description = "Mintys ir tekstai apie kalbas ir programų inžineriją, \"pasidaryk pats\" techniniai gidai"
    github = "https://github.com/AzisK"
    twitter = "https://twitter.com/XXX"
    email = "azuolas.krusna@yahoo.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"
    ShowReadingTime = true

[Permalinks]
    post = "/:filename/"
    